platform :ios, '7.0'
#use_frameworks!
xcodeproj 'ConnectSDK'
target 'ConnectSDK' do
  pod 'LGConnectSDK', :path => './'
end

post_install do |installer|
    installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
        configuration.build_settings['ENABLE_BITCODE'] = 'NO'
    end
end
